package com.github.trace.entity;

public class BpFields {

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.biz_id
	 *
	 * @mbggenerated
	 */
	private Integer bizId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.biz_name
	 *
	 * @mbggenerated
	 */
	private String bizName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.con_name
	 *
	 * @mbggenerated
	 */
	private String conName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.job_id
	 *
	 * @mbggenerated
	 */
	private Integer jobId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.table_id
	 *
	 * @mbggenerated
	 */
	private Integer tableId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.table_name
	 *
	 * @mbggenerated
	 */
	private String tableName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.field_name
	 *
	 * @mbggenerated
	 */
	private String fieldName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.desensitize
	 *
	 * @mbggenerated
	 */
	private String desensitize;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_fields.partition
	 *
	 * @mbggenerated
	 */
	private String partition;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.id
	 *
	 * @return the value of bp_fields.id
	 * @mbggenerated
	 */
	public Integer getId() {

		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.id
	 *
	 * @param id the value for bp_fields.id
	 * @mbggenerated
	 */
	public void setId( Integer id ) {

		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.biz_id
	 *
	 * @return the value of bp_fields.biz_id
	 * @mbggenerated
	 */
	public Integer getBizId() {

		return bizId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.biz_id
	 *
	 * @param bizId the value for bp_fields.biz_id
	 * @mbggenerated
	 */
	public void setBizId( Integer bizId ) {

		this.bizId = bizId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.biz_name
	 *
	 * @return the value of bp_fields.biz_name
	 * @mbggenerated
	 */
	public String getBizName() {

		return bizName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.biz_name
	 *
	 * @param bizName the value for bp_fields.biz_name
	 * @mbggenerated
	 */
	public void setBizName( String bizName ) {

		this.bizName = bizName == null ? null : bizName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.con_name
	 *
	 * @return the value of bp_fields.con_name
	 * @mbggenerated
	 */
	public String getConName() {

		return conName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.con_name
	 *
	 * @param conName the value for bp_fields.con_name
	 * @mbggenerated
	 */
	public void setConName( String conName ) {

		this.conName = conName == null ? null : conName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.job_id
	 *
	 * @return the value of bp_fields.job_id
	 * @mbggenerated
	 */
	public Integer getJobId() {

		return jobId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.job_id
	 *
	 * @param jobId the value for bp_fields.job_id
	 * @mbggenerated
	 */
	public void setJobId( Integer jobId ) {

		this.jobId = jobId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.table_id
	 *
	 * @return the value of bp_fields.table_id
	 * @mbggenerated
	 */
	public Integer getTableId() {

		return tableId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.table_id
	 *
	 * @param tableId the value for bp_fields.table_id
	 * @mbggenerated
	 */
	public void setTableId( Integer tableId ) {

		this.tableId = tableId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.table_name
	 *
	 * @return the value of bp_fields.table_name
	 * @mbggenerated
	 */
	public String getTableName() {

		return tableName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.table_name
	 *
	 * @param tableName the value for bp_fields.table_name
	 * @mbggenerated
	 */
	public void setTableName( String tableName ) {

		this.tableName = tableName == null ? null : tableName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.field_name
	 *
	 * @return the value of bp_fields.field_name
	 * @mbggenerated
	 */
	public String getFieldName() {

		return fieldName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.field_name
	 *
	 * @param fieldName the value for bp_fields.field_name
	 * @mbggenerated
	 */
	public void setFieldName( String fieldName ) {

		this.fieldName = fieldName == null ? null : fieldName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.desensitize
	 *
	 * @return the value of bp_fields.desensitize
	 * @mbggenerated
	 */
	public String getDesensitize() {

		return desensitize;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.desensitize
	 *
	 * @param desensitize the value for bp_fields.desensitize
	 * @mbggenerated
	 */
	public void setDesensitize( String desensitize ) {

		this.desensitize = desensitize == null ? null : desensitize.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_fields.partition
	 *
	 * @return the value of bp_fields.partition
	 * @mbggenerated
	 */
	public String getPartition() {

		return partition;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_fields.partition
	 *
	 * @param partition the value for bp_fields.partition
	 * @mbggenerated
	 */
	public void setPartition( String partition ) {

		this.partition = partition == null ? null : partition.trim();
	}
}