package com.github.trace.entity;

public class BpTarget {

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_target.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_target.name
	 *
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_target.type
	 *
	 * @mbggenerated
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_target.ip
	 *
	 * @mbggenerated
	 */
	private String ip;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_target.port
	 *
	 * @mbggenerated
	 */
	private Integer port;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_target.path
	 *
	 * @mbggenerated
	 */
	private String path;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column bp_target.value
	 *
	 * @mbggenerated
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_target.id
	 *
	 * @return the value of bp_target.id
	 * @mbggenerated
	 */
	public Integer getId() {

		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_target.id
	 *
	 * @param id the value for bp_target.id
	 * @mbggenerated
	 */
	public void setId( Integer id ) {

		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_target.name
	 *
	 * @return the value of bp_target.name
	 * @mbggenerated
	 */
	public String getName() {

		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_target.name
	 *
	 * @param name the value for bp_target.name
	 * @mbggenerated
	 */
	public void setName( String name ) {

		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_target.type
	 *
	 * @return the value of bp_target.type
	 * @mbggenerated
	 */
	public String getType() {

		return type;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_target.type
	 *
	 * @param type the value for bp_target.type
	 * @mbggenerated
	 */
	public void setType( String type ) {

		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_target.ip
	 *
	 * @return the value of bp_target.ip
	 * @mbggenerated
	 */
	public String getIp() {

		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_target.ip
	 *
	 * @param ip the value for bp_target.ip
	 * @mbggenerated
	 */
	public void setIp( String ip ) {

		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_target.port
	 *
	 * @return the value of bp_target.port
	 * @mbggenerated
	 */
	public Integer getPort() {

		return port;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_target.port
	 *
	 * @param port the value for bp_target.port
	 * @mbggenerated
	 */
	public void setPort( Integer port ) {

		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_target.path
	 *
	 * @return the value of bp_target.path
	 * @mbggenerated
	 */
	public String getPath() {

		return path;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_target.path
	 *
	 * @param path the value for bp_target.path
	 * @mbggenerated
	 */
	public void setPath( String path ) {

		this.path = path == null ? null : path.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column bp_target.value
	 *
	 * @return the value of bp_target.value
	 * @mbggenerated
	 */
	public String getValue() {

		return value;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column bp_target.value
	 *
	 * @param value the value for bp_target.value
	 * @mbggenerated
	 */
	public void setValue( String value ) {

		this.value = value == null ? null : value.trim();
	}
}