package com.github.trace.entity;

public class buriedPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buried_point.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buried_point.key
     *
     * @mbggenerated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buried_point.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buried_point.key_type
     *
     * @mbggenerated
     */
    private String keyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buried_point.value_type
     *
     * @mbggenerated
     */
    private String valueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buried_point.biz_id
     *
     * @mbggenerated
     */
    private Integer bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buried_point.biz_name
     *
     * @mbggenerated
     */
    private String bizName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buried_point.regex
     *
     * @mbggenerated
     */
    private String regex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buried_point.id
     *
     * @return the value of buried_point.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buried_point.id
     *
     * @param id the value for buried_point.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buried_point.key
     *
     * @return the value of buried_point.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buried_point.key
     *
     * @param key the value for buried_point.key
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buried_point.value
     *
     * @return the value of buried_point.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buried_point.value
     *
     * @param value the value for buried_point.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buried_point.key_type
     *
     * @return the value of buried_point.key_type
     *
     * @mbggenerated
     */
    public String getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buried_point.key_type
     *
     * @param keyType the value for buried_point.key_type
     *
     * @mbggenerated
     */
    public void setKeyType(String keyType) {
        this.keyType = keyType == null ? null : keyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buried_point.value_type
     *
     * @return the value of buried_point.value_type
     *
     * @mbggenerated
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buried_point.value_type
     *
     * @param valueType the value for buried_point.value_type
     *
     * @mbggenerated
     */
    public void setValueType(String valueType) {
        this.valueType = valueType == null ? null : valueType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buried_point.biz_id
     *
     * @return the value of buried_point.biz_id
     *
     * @mbggenerated
     */
    public Integer getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buried_point.biz_id
     *
     * @param bizId the value for buried_point.biz_id
     *
     * @mbggenerated
     */
    public void setBizId(Integer bizId) {
        this.bizId = bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buried_point.biz_name
     *
     * @return the value of buried_point.biz_name
     *
     * @mbggenerated
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buried_point.biz_name
     *
     * @param bizName the value for buried_point.biz_name
     *
     * @mbggenerated
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buried_point.regex
     *
     * @return the value of buried_point.regex
     *
     * @mbggenerated
     */
    public String getRegex() {
        return regex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buried_point.regex
     *
     * @param regex the value for buried_point.regex
     *
     * @mbggenerated
     */
    public void setRegex(String regex) {
        this.regex = regex == null ? null : regex.trim();
    }
}