package com.github.trace.entity;

import java.util.Date;

public class DatabaseInfo {

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.biz_id
	 *
	 * @mbggenerated
	 */
	private Integer bizId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.biz_name
	 *
	 * @mbggenerated
	 */
	private String bizName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.name
	 *
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.db_name
	 *
	 * @mbggenerated
	 */
	private String dbName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.db_type
	 *
	 * @mbggenerated
	 */
	private String dbType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.db_url
	 *
	 * @mbggenerated
	 */
	private String dbUrl;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.db_port
	 *
	 * @mbggenerated
	 */
	private Integer dbPort;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.db_driver
	 *
	 * @mbggenerated
	 */
	private String dbDriver;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.db_username
	 *
	 * @mbggenerated
	 */
	private String dbUsername;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.db_password
	 *
	 * @mbggenerated
	 */
	private String dbPassword;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.db_encoding
	 *
	 * @mbggenerated
	 */
	private String dbEncoding;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.driver_clazz
	 *
	 * @mbggenerated
	 */
	private String driverClazz;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.connect_param
	 *
	 * @mbggenerated
	 */
	private String connectParam;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.user_id
	 *
	 * @mbggenerated
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column database_info.last_update
	 *
	 * @mbggenerated
	 */
	private Date lastUpdate;


	private String dbIns;

	public String getDbIns() {

		return dbIns;
	}

	public void setDbIns( String dbIns ) {

		this.dbIns = dbIns;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.id
	 *
	 * @return the value of database_info.id
	 * @mbggenerated
	 */
	public Integer getId() {

		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.id
	 *
	 * @param id the value for database_info.id
	 * @mbggenerated
	 */
	public void setId( Integer id ) {

		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.biz_id
	 *
	 * @return the value of database_info.biz_id
	 * @mbggenerated
	 */
	public Integer getBizId() {

		return bizId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.biz_id
	 *
	 * @param bizId the value for database_info.biz_id
	 * @mbggenerated
	 */
	public void setBizId( Integer bizId ) {

		this.bizId = bizId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.biz_name
	 *
	 * @return the value of database_info.biz_name
	 * @mbggenerated
	 */
	public String getBizName() {

		return bizName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.biz_name
	 *
	 * @param bizName the value for database_info.biz_name
	 * @mbggenerated
	 */
	public void setBizName( String bizName ) {

		this.bizName = bizName == null ? null : bizName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.name
	 *
	 * @return the value of database_info.name
	 * @mbggenerated
	 */
	public String getName() {

		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.name
	 *
	 * @param name the value for database_info.name
	 * @mbggenerated
	 */
	public void setName( String name ) {

		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.db_name
	 *
	 * @return the value of database_info.db_name
	 * @mbggenerated
	 */
	public String getDbName() {

		return dbName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.db_name
	 *
	 * @param dbName the value for database_info.db_name
	 * @mbggenerated
	 */
	public void setDbName( String dbName ) {

		this.dbName = dbName == null ? null : dbName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.db_type
	 *
	 * @return the value of database_info.db_type
	 * @mbggenerated
	 */
	public String getDbType() {

		return dbType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.db_type
	 *
	 * @param dbType the value for database_info.db_type
	 * @mbggenerated
	 */
	public void setDbType( String dbType ) {

		this.dbType = dbType == null ? null : dbType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.db_url
	 *
	 * @return the value of database_info.db_url
	 * @mbggenerated
	 */
	public String getDbUrl() {

		return dbUrl;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.db_url
	 *
	 * @param dbUrl the value for database_info.db_url
	 * @mbggenerated
	 */
	public void setDbUrl( String dbUrl ) {

		this.dbUrl = dbUrl == null ? null : dbUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.db_port
	 *
	 * @return the value of database_info.db_port
	 * @mbggenerated
	 */
	public Integer getDbPort() {

		return dbPort;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.db_port
	 *
	 * @param dbPort the value for database_info.db_port
	 * @mbggenerated
	 */
	public void setDbPort( Integer dbPort ) {

		this.dbPort = dbPort;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.db_driver
	 *
	 * @return the value of database_info.db_driver
	 * @mbggenerated
	 */
	public String getDbDriver() {

		return dbDriver;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.db_driver
	 *
	 * @param dbDriver the value for database_info.db_driver
	 * @mbggenerated
	 */
	public void setDbDriver( String dbDriver ) {

		this.dbDriver = dbDriver == null ? null : dbDriver.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.db_username
	 *
	 * @return the value of database_info.db_username
	 * @mbggenerated
	 */
	public String getDbUsername() {

		return dbUsername;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.db_username
	 *
	 * @param dbUsername the value for database_info.db_username
	 * @mbggenerated
	 */
	public void setDbUsername( String dbUsername ) {

		this.dbUsername = dbUsername == null ? null : dbUsername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.db_password
	 *
	 * @return the value of database_info.db_password
	 * @mbggenerated
	 */
	public String getDbPassword() {

		return dbPassword;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.db_password
	 *
	 * @param dbPassword the value for database_info.db_password
	 * @mbggenerated
	 */
	public void setDbPassword( String dbPassword ) {

		this.dbPassword = dbPassword == null ? null : dbPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.db_encoding
	 *
	 * @return the value of database_info.db_encoding
	 * @mbggenerated
	 */
	public String getDbEncoding() {

		return dbEncoding;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.db_encoding
	 *
	 * @param dbEncoding the value for database_info.db_encoding
	 * @mbggenerated
	 */
	public void setDbEncoding( String dbEncoding ) {

		this.dbEncoding = dbEncoding == null ? null : dbEncoding.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.driver_clazz
	 *
	 * @return the value of database_info.driver_clazz
	 * @mbggenerated
	 */
	public String getDriverClazz() {

		return driverClazz;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.driver_clazz
	 *
	 * @param driverClazz the value for database_info.driver_clazz
	 * @mbggenerated
	 */
	public void setDriverClazz( String driverClazz ) {

		this.driverClazz = driverClazz == null ? null : driverClazz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.connect_param
	 *
	 * @return the value of database_info.connect_param
	 * @mbggenerated
	 */
	public String getConnectParam() {

		return connectParam;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.connect_param
	 *
	 * @param connectParam the value for database_info.connect_param
	 * @mbggenerated
	 */
	public void setConnectParam( String connectParam ) {

		this.connectParam = connectParam == null ? null : connectParam.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.user_id
	 *
	 * @return the value of database_info.user_id
	 * @mbggenerated
	 */
	public String getUserId() {

		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.user_id
	 *
	 * @param userId the value for database_info.user_id
	 * @mbggenerated
	 */
	public void setUserId( String userId ) {

		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column database_info.last_update
	 *
	 * @return the value of database_info.last_update
	 * @mbggenerated
	 */
	public Date getLastUpdate() {

		return lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column database_info.last_update
	 *
	 * @param lastUpdate the value for database_info.last_update
	 * @mbggenerated
	 */
	public void setLastUpdate( Date lastUpdate ) {

		this.lastUpdate = lastUpdate;
	}
}