package com.github.trace.entity;

public class LevelTwoFields {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_two_fields.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_two_fields.level1_field_id
     *
     * @mbggenerated
     */
    private Integer level1FieldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_two_fields.level1_field_tag
     *
     * @mbggenerated
     */
    private String level1FieldTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_two_fields.level1_field_name
     *
     * @mbggenerated
     */
    private String level1FieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_two_fields.level2_field_name
     *
     * @mbggenerated
     */
    private String level2FieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_two_fields.level2_field_desc
     *
     * @mbggenerated
     */
    private String level2FieldDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_two_fields.id
     *
     * @return the value of level_two_fields.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_two_fields.id
     *
     * @param id the value for level_two_fields.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_two_fields.level1_field_id
     *
     * @return the value of level_two_fields.level1_field_id
     *
     * @mbggenerated
     */
    public Integer getLevel1FieldId() {
        return level1FieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_two_fields.level1_field_id
     *
     * @param level1FieldId the value for level_two_fields.level1_field_id
     *
     * @mbggenerated
     */
    public void setLevel1FieldId(Integer level1FieldId) {
        this.level1FieldId = level1FieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_two_fields.level1_field_tag
     *
     * @return the value of level_two_fields.level1_field_tag
     *
     * @mbggenerated
     */
    public String getLevel1FieldTag() {
        return level1FieldTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_two_fields.level1_field_tag
     *
     * @param level1FieldTag the value for level_two_fields.level1_field_tag
     *
     * @mbggenerated
     */
    public void setLevel1FieldTag(String level1FieldTag) {
        this.level1FieldTag = level1FieldTag == null ? null : level1FieldTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_two_fields.level1_field_name
     *
     * @return the value of level_two_fields.level1_field_name
     *
     * @mbggenerated
     */
    public String getLevel1FieldName() {
        return level1FieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_two_fields.level1_field_name
     *
     * @param level1FieldName the value for level_two_fields.level1_field_name
     *
     * @mbggenerated
     */
    public void setLevel1FieldName(String level1FieldName) {
        this.level1FieldName = level1FieldName == null ? null : level1FieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_two_fields.level2_field_name
     *
     * @return the value of level_two_fields.level2_field_name
     *
     * @mbggenerated
     */
    public String getLevel2FieldName() {
        return level2FieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_two_fields.level2_field_name
     *
     * @param level2FieldName the value for level_two_fields.level2_field_name
     *
     * @mbggenerated
     */
    public void setLevel2FieldName(String level2FieldName) {
        this.level2FieldName = level2FieldName == null ? null : level2FieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_two_fields.level2_field_desc
     *
     * @return the value of level_two_fields.level2_field_desc
     *
     * @mbggenerated
     */
    public String getLevel2FieldDesc() {
        return level2FieldDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_two_fields.level2_field_desc
     *
     * @param level2FieldDesc the value for level_two_fields.level2_field_desc
     *
     * @mbggenerated
     */
    public void setLevel2FieldDesc(String level2FieldDesc) {
        this.level2FieldDesc = level2FieldDesc == null ? null : level2FieldDesc.trim();
    }
}