package com.github.trace.entity;

public class M99Fields {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.m1_id
     *
     * @mbggenerated
     */
    private Integer levelOneId;

    public Integer getLevelTwoId() {
        return levelTwoId;
    }

    public void setLevelTwoId(Integer levelTwoId) {
        this.levelTwoId = levelTwoId;
    }

    private Integer levelTwoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.m1_name
     *
     * @mbggenerated
     */
    private String m1Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.field_name
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.field_desc
     *
     * @mbggenerated
     */
    private String fieldDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.field_type
     *
     * @mbggenerated
     */
    private String fieldType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.field_regex
     *
     * @mbggenerated
     */
    private String fieldRegex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.id
     *
     * @return the value of m99_fields.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.id
     *
     * @param id the value for m99_fields.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.m1_id
     *
     * @return the value of m99_fields.m1_id
     *
     * @mbggenerated
     */
    public Integer getLevelOneId() {
        return levelOneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.m1_id
     *
     * @param levelOneId the value for m99_fields.m1_id
     *
     * @mbggenerated
     */
    public void setLevelOneId(Integer levelOneId) {
        this.levelOneId = levelOneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.m1_name
     *
     * @return the value of m99_fields.m1_name
     *
     * @mbggenerated
     */
    public String getM1Name() {
        return m1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.m1_name
     *
     * @param m1Name the value for m99_fields.m1_name
     *
     * @mbggenerated
     */
    public void setM1Name(String m1Name) {
        this.m1Name = m1Name == null ? null : m1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.field_name
     *
     * @return the value of m99_fields.field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.field_name
     *
     * @param fieldName the value for m99_fields.field_name
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.field_desc
     *
     * @return the value of m99_fields.field_desc
     *
     * @mbggenerated
     */
    public String getFieldDesc() {
        return fieldDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.field_desc
     *
     * @param fieldDesc the value for m99_fields.field_desc
     *
     * @mbggenerated
     */
    public void setFieldDesc(String fieldDesc) {
        this.fieldDesc = fieldDesc == null ? null : fieldDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.field_type
     *
     * @return the value of m99_fields.field_type
     *
     * @mbggenerated
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.field_type
     *
     * @param fieldType the value for m99_fields.field_type
     *
     * @mbggenerated
     */
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType == null ? null : fieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.field_regex
     *
     * @return the value of m99_fields.field_regex
     *
     * @mbggenerated
     */
    public String getFieldRegex() {
        return fieldRegex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.field_regex
     *
     * @param fieldRegex the value for m99_fields.field_regex
     *
     * @mbggenerated
     */
    public void setFieldRegex(String fieldRegex) {
        this.fieldRegex = fieldRegex == null ? null : fieldRegex.trim();
    }
}
