package com.github.trace.entity;

public class M99Fields {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.m1_id
     *
     * @mbggenerated
     */
    private Integer m1Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.m1_name
     *
     * @mbggenerated
     */
    private String m1Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.field_name
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m99_fields.field_desc
     *
     * @mbggenerated
     */
    private String fieldDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.id
     *
     * @return the value of m99_fields.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.id
     *
     * @param id the value for m99_fields.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.m1_id
     *
     * @return the value of m99_fields.m1_id
     *
     * @mbggenerated
     */
    public Integer getM1Id() {
        return m1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.m1_id
     *
     * @param m1Id the value for m99_fields.m1_id
     *
     * @mbggenerated
     */
    public void setM1Id(Integer m1Id) {
        this.m1Id = m1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.m1_name
     *
     * @return the value of m99_fields.m1_name
     *
     * @mbggenerated
     */
    public String getM1Name() {
        return m1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.m1_name
     *
     * @param m1Name the value for m99_fields.m1_name
     *
     * @mbggenerated
     */
    public void setM1Name(String m1Name) {
        this.m1Name = m1Name == null ? null : m1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.field_name
     *
     * @return the value of m99_fields.field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.field_name
     *
     * @param fieldName the value for m99_fields.field_name
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m99_fields.field_desc
     *
     * @return the value of m99_fields.field_desc
     *
     * @mbggenerated
     */
    public String getFieldDesc() {
        return fieldDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m99_fields.field_desc
     *
     * @param fieldDesc the value for m99_fields.field_desc
     *
     * @mbggenerated
     */
    public void setFieldDesc(String fieldDesc) {
        this.fieldDesc = fieldDesc == null ? null : fieldDesc.trim();
    }
}