package com.github.trace.entity;

public class navigationItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation_item.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation_item.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation_item.parent_name
     *
     * @mbggenerated
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation_item.child_id
     *
     * @mbggenerated
     */
    private Integer childId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigation_item.child_name
     *
     * @mbggenerated
     */
    private String childName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation_item.id
     *
     * @return the value of navigation_item.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation_item.id
     *
     * @param id the value for navigation_item.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation_item.parent_id
     *
     * @return the value of navigation_item.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation_item.parent_id
     *
     * @param parentId the value for navigation_item.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation_item.parent_name
     *
     * @return the value of navigation_item.parent_name
     *
     * @mbggenerated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation_item.parent_name
     *
     * @param parentName the value for navigation_item.parent_name
     *
     * @mbggenerated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation_item.child_id
     *
     * @return the value of navigation_item.child_id
     *
     * @mbggenerated
     */
    public Integer getChildId() {
        return childId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation_item.child_id
     *
     * @param childId the value for navigation_item.child_id
     *
     * @mbggenerated
     */
    public void setChildId(Integer childId) {
        this.childId = childId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigation_item.child_name
     *
     * @return the value of navigation_item.child_name
     *
     * @mbggenerated
     */
    public String getChildName() {
        return childName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigation_item.child_name
     *
     * @param childName the value for navigation_item.child_name
     *
     * @mbggenerated
     */
    public void setChildName(String childName) {
        this.childName = childName == null ? null : childName.trim();
    }
}