package com.github.trace.mapper;

import com.github.trace.entity.buriedPointList;

public interface buriedPointListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buried_point_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buried_point_list
     *
     * @mbggenerated
     */
    int insert(buriedPointList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buried_point_list
     *
     * @mbggenerated
     */
    int insertSelective(buriedPointList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buried_point_list
     *
     * @mbggenerated
     */
    buriedPointList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buried_point_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(buriedPointList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buried_point_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(buriedPointList record);
}