package com.github.trace.mapper;

import com.github.trace.entity.navigationItem;

public interface navigationItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_item
     *
     * @mbggenerated
     */
    int insert(navigationItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_item
     *
     * @mbggenerated
     */
    int insertSelective(navigationItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_item
     *
     * @mbggenerated
     */
    navigationItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(navigationItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(navigationItem record);
}